apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "travis.fullname" . }}
  labels:
    app: {{ template "travis.name" . }}
    chart: {{ template "travis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  RAILS_ENV: production
  RACK_ENV: production
  API_ENDPOINT: travis-api
