apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "travis.fullname" . }}
  labels:
    app: {{ template "travis.name" . }}
    chart: {{ template "travis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  API_ENDPOINT: "https://{{ .Values.ingress.hosts.api }}"
  DATABASE_URL: "postgres://travis:travis@travis-postgresql/travis_production"
  DISABLE_SENTRY: "true"
  PUBLIC_MODE: "true"
  RACK_ENV: production
  RAILS_ENV: production
  REDIS_URL: "redis://{{ template "travis.fullname" . }}-redis:80"
  TRAVIS_INGRESS_HOST: {{ .Values.ingress.hosts.web }}
