apiVersion: v1
kind: Service
metadata:
  name: {{ template "travis.fullname" . }}-redis
  labels:
    app: {{ template "travis.name" . }}
    chart: {{ template "travis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "travis.name" . }}-redis
    release: {{ .Release.Name }}
